# observability/values/grafana.values.yaml
adminPassword: admin  # change or externalize via secret

service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://kube-prometheus-stack-prometheus.observability.svc:9090
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc:3100

